
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" 
      - "80:80/tcp"

    networks:
     ph_network:
       ipv4_address: 10.0.0.2
       priority: 1000
     ph_bridge:
       ipv4_address: 172.28.0.2
       priority: 900

    environment:
      TZ: 'America/Chicago' 
      WEBPASSWORD: 'password'
      DNSMASQ_LISTENING: local
      PIHOLE_DNS_: 'IP_ADDRESS#5053'

    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN


  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      ph_bridge:
        ipv4_address: 172.28.0.2
    volumes:
      # Mount your Unbound config folder (must contain unbound.conf)
      - ./unbound:/opt/unbound/etc/unbound:ro
      # Optional: persist Unbound state (e.g., root.key) separately
      - ./unbound-state:/var/lib/unbound