
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" 
      - "80:80/tcp"

    network_mode: host
    environment:
      TZ: 'America/Chicago' 
      WEBPASSWORD: 'password'
      DNSMASQ_LISTENING: local
      PIHOLE_DNS_: 'IP_ADDRESS#5053'

    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN