version: "3.8"

services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      ph_bridge:
        ipv4_address: 172.28.0.2
    volumes:

      - ./unbound:/opt/unbound/etc/unbound:ro

      - ./unbound-state:/var/lib/unbound

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    depends_on:
      - unbound
    networks:
      ph_network:
        ipv4_address: 10.0.0.2
      ph_bridge:
        ipv4_address: 172.28.0.3
    environment:
      TZ: America/Chicago
      WEBPASSWORD: "change-me"
      DNSMASQ_LISTENING: "all"
      FTLCONF_LOCAL_IPV4: "10.0.0.2"
      PIHOLE_DNS_: "172.28.0.2#53"  
    cap_add:
      - NET_ADMIN
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d

networks:
  ph_network:
    driver: macvlan
    driver_opts:
      parent: enp3s0        
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
          ip_range: 10.0.0.2/32
  ph_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
