
services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      ph_bridge:
        ipv4_address: 172.28.0.2
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/'

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    depends_on:
      - unbound
    networks:
      ph_network:
        ipv4_address: 10.0.0.2
      ph_bridge:
        ipv4_address: 172.28.0.3
    environment:
      TZ: America/Chicago
      WEBPASSWORD: "change-me"
      DNSMASQ_LISTENING: "all"
      FTLCONF_LOCAL_IPV4: "10.0.0.2"
      PIHOLE_DNS_: "172.28.0.2#53"  
    cap_add:
      - NET_ADMIN
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d

networks:
  ph_bridge:
    external: true
    name: ph_bridge
  ph_network:
    external: true
    name: ph_network