
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      TZ: 'America/Chicago'  # Change to your timezone
      WEBPASSWORD: 'changeme'  # Change this password!
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN

  pihole-exporter:
    image: pglittle/pihole_exporter:latest
    restart: unless-stopped
    ports:
      - "9617:9617"
    environment:
      PIHOLE_HOST: http://localhost/admin
      PIHOLE_TOKEN: "zEgdNhlGwviup1EX3+AFR4flKV+ZuLiX2kLy0l6+7lM="