    
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" 
      - "80:80/tcp"
    networks:
     ph_network:
       ipv4_address: 10.0.0.2
       priority: 1000
     ph_bridge:
       ipv4_address: 172.28.0.3
       priority: 900
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'password'
      DNSMASQ_LISTENING: local
      PIHOLE_DNS_: '172.28.0.2#53'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: "mvance/unbound:latest"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks: 
     ph_network:
       ipv4_address: 172.28.0.2
    volumes:
      - './unbound/unbound.conf:/opt/unbound/etc/unbound/'
    restart: unless-stopped
networks:
    ph_bridge:
      driver: bridge
      ipam:
        config:
          - subnet: 172.28.0.0/24
            gateway: 172.28.0.1
            ip_range: 172.28.0.2/32
    ph_network:
      name: ph_network
      driver: macvlan
      driver_opts:
        parent: enp3s0
      ipam:
        config:
          - subnet: 10.0.0.0/24
            ip_range: 10.0.0.0/24
            gateway: 10.0.0.1