    
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      ph_bridge:
        priority: 1000    
        ipv4_address: 172.31.0.3
      ph_network: {}  

    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'password'
      DNSMASQ_LISTENING: 'all'
      PIHOLE_DNS_: '172.31.0.2#53'
      FTLCONF_LOCAL_IPV4: "10.0.0.2"
  
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'

    depends_on:
    - unbound

    restart: unless-stopped

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    ports:
      - "5335:53/udp"
      - "5335:53/tcp"
    volumes:
      - ./unbound:/opt/unbound/etc/unbound   # your config folder
      - ./unbound-state:/var/lib/unbound    # DNSSEC state (root.key)
    restart: unless-stopped

networks:
    ph_bridge:
      driver: bridge
      ipam:
        config:
          - subnet: 172.31.0.0/24
            
    ph_network:
      name: ph_network
      driver: macvlan
      driver_opts:
        parent: enp3s0
      ipam:
        config:
          - subnet: 10.0.0.0/24
            ip_range: 10.0.0.2/32
            gateway: 10.0.0.1