
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      TZ: 'America/Chicago'  # Change to your timezone
      WEBPASSWORD: 'changeme'  # Change this password!
      FTL_CMD: "local-ttl=300"
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN