services:
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: unless-stopped
    
    network_mode: host

    ports:
      - "5053:53/tcp"
      - "5053:53/udp"

    volumes:
      - ./unbound:/opt/unbound/etc/unbound
